[package]
name = "mac_grid_fluid"
version = "0.1.0"
edition = "2021"

[dependencies]
glow = "0.13.0"
glam = "0.27.0"
sdl2 = "0.35.2"
posh = { git = "https://github.com/leod/posh.git", rev = "ebdde18a7a223a235fc78aa59cc1369d2b0db9b8" }
